trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: mvn clean install
  displayName: 'Build with Maven'  
- script: java -jar target/p9fix-1.0-SNAPSHOT.jar
  displayName: 'Running jar'